Feature/new nagivation
ropekonsti/konsti pull request #15
Opened 2020-11-15 17:23 UTC by nkauppila

- Please do not create a Pull Request without discussing the change first.
- Please provide enough information so others can review your pull request.

2021-01-07 16:46 UTC, Archinowsk commented
Kehitysidea tähän tai tulevaan PR:ään. 

Korostus siihen sivuun, mikä on valittuna:
![image](https://user-images.githubusercontent.com/1327412/103919237-7f324d00-5118-11eb-8e61-9b65c6da8d2c.png)

2021-01-07 16:48 UTC, Archinowsk commented
Onkohan kirjautunut käyttäjänimi sellainen, että se pitäisi olla aina näkyvissä? Mietin että tuleeko siitä muuten fiilis, että onko kirjautunut vai ei?

![image](https://user-images.githubusercontent.com/1327412/103919470-bbfe4400-5118-11eb-9c53-0e9f95a557c4.png)

2021-01-07 16:51 UTC, Archinowsk commented
Kun katsoo ilmoittautumissivua mobiilinäkymässä niin drag and drop ei toimi. Varmaan joku selaimen juttu, koska pitäisi toimia natiivilaitteilla. Vielä oudompaa on, että sain sen kerran toimimaan mutta en ole ihan varma, että mitä tein :D.

![loader9](https://user-images.githubusercontent.com/1327412/103919907-4b0b5c00-5119-11eb-8547-2afd54111135.gif)

2021-01-07 17:04 UTC, Archinowsk requested changes
Hyvän näköistä kamaa! Pari kommenttia lähinnä aikaisempiin konventioihin liittyen.

2021-01-07 17:04 UTC, Archinowsk commented on client/src/components/Navigation.tsx
> +const LoggedInUserNavigation = (props: {
Laittaisin tän melkein omaan tiedostoon. Oon koittanut pysyä aika tiukasti yksi tiedosto / yksi komponentti käytännössä vaikka komponentti olisi esim vain ~10 riviä pitkä. Useempi komponentti + styled-components tyylit tekee tiedostoista muuten vähän pitkiä.

2021-01-07 17:04 UTC, Archinowsk commented on client/src/components/Navigation.tsx
> +const UserNavigation = (props: { onSelect: () => void }): ReactElement => {
Laittaisin tän melkein omaan tiedostoon. Oon koittanut pysyä aika tiukasti yksi tiedosto / yksi komponentti käytännössä vaikka komponentti olisi esim vain ~10 riviä pitkä. Useempi komponentti + styled-components tyylit tekee tiedostoista muuten vähän pitkiä.

2021-01-24 12:27 UTC, nkauppila commented
> Onkohan kirjautunut käyttäjänimi sellainen, että se pitäisi olla aina näkyvissä? Mietin että tuleeko siitä muuten fiilis, että onko kirjautunut vai ei?
> 
> ![image](https://user-images.githubusercontent.com/1327412/103919470-bbfe4400-5118-11eb-9c53-0e9f95a557c4.png)

Samaa mieltä tästä. Ajattelin, että kunhan tuo muotoutuu tuosta vielä eteenpäin niin näkee ehkä paremmin miten se kannattaa indikoida käyttäjälle.

2021-01-24 13:10 UTC, nkauppila commented
> Onkohan kirjautunut käyttäjänimi sellainen, että se pitäisi olla aina näkyvissä? Mietin että tuleeko siitä muuten fiilis, että onko kirjautunut vai ei?
> 
> ![image](https://user-images.githubusercontent.com/1327412/103919470-bbfe4400-5118-11eb-9c53-0e9f95a557c4.png)

Hyvä huomio! Tää oli unohtunut mutta nyt lisätty.

2021-01-24 13:11 UTC, nkauppila commented on client/src/app/Routes.tsx
> -        </StyledRoutes>
Tätä voidaan siitiä sitä mukaan kun poistetaan vanhoja sivuja. Mutta nää olisi nyt poistettu.

2021-01-24 13:12 UTC, nkauppila commented
> Kun katsoo ilmoittautumissivua mobiilinäkymässä niin drag and drop ei toimi. Varmaan joku selaimen juttu, koska pitäisi toimia natiivilaitteilla. Vielä oudompaa on, että sain sen kerran toimimaan mutta en ole ihan varma, että mitä tein :D.
> 
> ![loader9](https://user-images.githubusercontent.com/1327412/103919907-4b0b5c00-5119-11eb-8547-2afd54111135.gif)

Tää on kyllä jännä. Mulla kävi samanlailla, eli sain kerran siirrettyä. Siitä tuli virhe koska mulla oli jo kolme valittua niin sen jälkeen ei enää siirto onnistunut.

2021-01-24 15:26 UTC, Archinowsk commented
Nää `data-testkey` attribuutit ei taida olla enää missään. Cypress-testit käyttää niitä. Cypress-testejä ei tällä hetkellä vielä ajella osana CI-buildia mutta voisin koittaa ottaa ne käyttöön piakkoin. 

Tää lähinnä tiedoksi, että jos buildi ei jossakin kohtaa menekkään enää läpi Cypress-testien takia. Siellä on nyt yksi pieni testi, mikä vaan kattoo, että admin-käyttäjän login toimii: https://github.com/ropekonsti/konsti/blob/master/client/cypress/integration/login.spec.ts

![image](https://user-images.githubusercontent.com/1327412/105634799-896a8000-5e68-11eb-914b-2e6392942894.png)

2021-01-24 15:28 UTC, Archinowsk approved these changes

2021-01-24 15:28 UTC, Archinowsk commented
Hyvältä näyttää!

2021-01-24 16:19 UTC, merged